# Generated by Django 3.2.3 on 2021-05-25 14:26

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_all_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='all_user',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
